Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d63de463e6604d0a
      Tags:
        - Key: "Name"
          Value: !Join 
            - " "
            - - "My Instance in"
              - !Ref AWS::Region